[package]
name = "quick_start"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ciborium = "0.2.1"
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
ic-stable-structures = { path = "../../../" }
serde.workspace = true
